In [1]:
x = 'abc'
y= '10.5'

In [2]:
int(y)

ValueError: invalid literal for int() with base 10: '10.5'

In [3]:
z = 1010
int(z)

1010

In [4]:
bin(2)

'0b10'

In [5]:
oct(10)

'0o12'

In [6]:
hex(15)

'0xf'

In [7]:
x<y

False

In [8]:
ascii('a')

"'a'"

In [9]:
ord('a')

97

In [10]:
ord('1')

49

In [11]:
'abc'<10

TypeError: '<' not supported between instances of 'str' and 'int'

In [12]:
10<'abc'

TypeError: '<' not supported between instances of 'int' and 'str'

In [13]:
True < False

False

In [15]:
# Palindrome
s = "madam"
if s == s[::-1]:
    print("palidrome")
else:
    print("Not palindrome")

palidrome


In [18]:
# Validation of the strings
# Validations for name of a person - 1. No number 2. No special char
name = 'Deepali@'
if name.isalpha():
    print("Valid")
else:
    print("Invalid")

Invalid


In [ ]:
# Validations of Credit card number - all digits, 16 digits

In [8]:
d = 1234567898765
if len(str(d))== 16:
    if (str(d)).isdigit():
        print('Valid')
else:
    print('invalid')

invalid


In [19]:
# "Hello World"
# Read "World"
s = "Hello World"
s[6:]

'World'

In [20]:
s.split()[1]

'World'

In [21]:
s[-5:]

'World'

In [24]:
date = '04/03/2024'
l = date.split('/')
day,month,year = l[0],l[1],l[2]

In [25]:
day,month,year

('04', '03', '2024')

In [28]:
day,month,year = date[:2], date[3:5],date[6:]
day,month,year

('04', '03', '2024')

In [9]:
s = 'madam'
for i in range(len(s)):
    if s[i] != s[len(s)-1-i]: # in the first iteration 0--> last index ; 1 --> second last index
        print("Not palindrome")
        break
else:
    print("Palidrome")

Palidrome


In [11]:
for i in range (len(s)):
    print(i)

0
1
2
3
4


In [16]:
n = 4
for i in range (2,n):
    if n%i == 0:
        print('Not prime')
        break
else:
    print('prime')

Not prime


In [40]:
s = " Hello World "
s.strip()

'Hello World'

In [42]:
s.rstrip()

' Hello World'

In [43]:
l = ['C','C++','Python','SQL']
l.sort()

In [44]:
l

['C', 'C++', 'Python', 'SQL']

In [46]:
sorted(l,reverse=True)

['SQL', 'Python', 'C++', 'C']

In [47]:
l

['C', 'C++', 'Python', 'SQL']

In [48]:
l.sort(key=len)

In [49]:
l

['C', 'C++', 'SQL', 'Python']

In [50]:
def m(no):
    return no%3

In [51]:
l1 = [10,20,40,30,55]
l1.sort(key =m)

In [52]:
l1

[30, 10, 40, 55, 20]

In [53]:
# insert, append and extend
l1.extend((35,45))
l1

[30, 10, 40, 55, 20, 35, 45]

In [1]:
L=[1,2,3,4,5]
for i in L:
    print(i,len(L))
    L.remove(i) #[2,3,4,5] [2,4,5]
print(L)

1 5
3 4
5 3
[2, 4]


In [58]:
# remove and pop
l.pop(10) # 10 is index

IndexError: pop index out of range

In [59]:
l.pop()

'Python'

In [60]:
# Given a 4 digit number, reverse number without type casting
num = 1234
reverse= 0
while num != 0:
        rem = num % 10 # 4 ; 3 ; 2 ;1
        reverse = reverse * 10 + rem # 4 ; 43 ;432 ; 4321
        num = num // 10 # 123 ; 12 ; 1 ;0
print(reverse)


4321


In [17]:
num = 1234
rev = int(str(num)[::-1])
rev

4321

In [62]:
l = [1,2,3,4,5,2,3,7]
# Remove all 2
print(l.count(2))
for i in range(l.count(2)):
    l.remove(2)
l

2


[1, 3, 4, 5, 3, 7]

In [65]:
l = [1,2,3,4,5,2,3,7,1,8,3]
# Show all duplicates
dup = []
for i in set(l):
    if l.count(i)>1:
        dup.append(i)
dup

[1, 2, 3]

In [66]:
s = set(l)
list(s)

[1, 2, 3, 4, 5, 7, 8]

In [67]:
asci = [ord(i) for i in 'Deepali']
asci

[68, 101, 101, 112, 97, 108, 105]

In [68]:
large = [i for i in ['a','xyz','assdfs','sdfsd','er','tt'] if len(i)>4]
large

['assdfs', 'sdfsd']

In [3]:
list1 = [12,23,34,4,54,54]
sq = [i*2 for i in list1 if i%2==0]
sq

[24, 68, 8, 108, 108]

In [6]:
[i*2 for i in list1]

[24, 46, 68, 8, 108, 108]

In [72]:
nest_list = [[i+j for i in range(3)] for j in range(1,6,3)]
nest_list

[[1, 2, 3], [4, 5, 6]]

In [23]:
for j in (range(1,6,3)):
    print(j)

1
4


In [24]:
for i in (range(3)):
    print(i)

0
1
2


In [26]:
nest_list = [[i for i in range(3)] for j in range(2)]
nest_list

[[0, 1, 2], [0, 1, 2]]

In [31]:
# Common values present in two lists. 
list1 = [12,23,34,4,54,54,4]
list2 = [12,23,7,8,9,4,12]
s = set()

for i in list1:
    if i in list2:
        s.add(i)
s

{4, 12, 23}

In [33]:
l = [i for i in list1 if i in list2]
list(set(l))

[12, 4, 23]

In [49]:
# Values in a list if the index are divisible by given integer. 
list1 = [12, 23, 34, 4, 54, 54, 4]
n = 2
l = [list1[i] for i in range(1,len(list1)) if i % n == 0]
print(l)

[34, 54, 4]


In [53]:
# • Consonants in a given string  
a='abcdEfghi123'
l = [i for i in a if i.isalpha() and i.lower() not in 'aeiou']
l

['b', 'c', 'd', 'f', 'g', 'h']

In [59]:
# missing vowels in a given string.
a='abcdEfghi123'
vow = set('aeiou')
l = {i.lower() for i in a if i.lower() in 'aeiou'}
print(l)
print(list(vow - l))

{'a', 'i', 'e'}
['u', 'o']


In [60]:
import seaborn as sns
import numpy as np
import pandas as pd

In [61]:
# • Find null values from dataset 
df = sns.load_dataset('titanic')
df.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [62]:
df.isnull().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [67]:
df.isnull().sum(axis=1)

0      1
1      0
2      1
3      0
4      1
      ..
886    1
887    0
888    2
889    0
890    1
Length: 891, dtype: int64

In [72]:
# Filter the data (whose gender is female, above 30yrs and doesn't have a child)
df[(df['sex']=='female') & (df['age']>30) & (df['parch'] == 0)].head(2)

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
1         1       1  female  38.0      1      0  71.2833        C  First   
3         1       1  female  35.0      1      0  53.1000        S  First   

     who  adult_male deck  embark_town alive  alone  
1  woman       False    C    Cherbourg   yes  False  
3  woman       False    C  Southampton   yes  False

In [73]:
# Python program to swap to numbers in a list 
def swap(l1,l2):
    l1,l2 = l2,l1
    return l1,l2

In [75]:
def swap_no(l,ind1,ind2):
    if 0<ind1<len(l) and 0<ind2<len(l):
        l[ind1],l[ind2] = l[ind2],l[ind1]
        return l
    else:
        print('Invalid index range')

In [78]:
list1 = [1,2,3,4,5]
swap_no(list1,2,3)

[1, 2, 4, 3, 5]

In [85]:
# Python code to write Fibonacci series -- 7
a = 0
b = 1

print(a,b,end=' ') 
for i in range (2,7):
    temp = a + b
    a = b
    b = temp
    print(temp,end=' ')
    

0 1 1 2 3 5 8 

In [86]:
# Write a program to print factorial number

def fact(n):
    if n==0:
        return 1
    else:
        return n*fact(n-1)

In [8]:
no = int(input("Enter a number: "))
fact = 1

if no < 0:
    print("Factorial is not defined for negative numbers.")
elif no == 0:
    print("Factorial of 0 is 1.")
else:
    for i in range(1, no + 1):
        fact *= i

    print('Factorial =', fact)

Enter a number: 5
Factorial = 120


In [111]:
# • Sort a given array 
a = np.arange(1,13).reshape(3,4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [126]:
np.random.seed(10)
a=np.random.randint(1,100,12).reshape(3,4)
a.sort(axis=1)
a

array([[10, 16, 29, 65],
       [ 9, 30, 90, 94],
       [ 1, 37, 41, 74]])

In [127]:
a[::-1]

array([[ 1, 37, 41, 74],
       [ 9, 30, 90, 94],
       [10, 16, 29, 65]])

In [130]:
b=a[::-1,::-1]
b

array([[74, 41, 37,  1],
       [94, 90, 30,  9],
       [65, 29, 16, 10]])

In [ ]:
# • consonant will be shifted to 3rd right 
# • Example: zap ---> dAs"

In [134]:
# Even no
eva = list(filter(lambda x: x%2==0, range(1,21)))
eva

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20]

In [135]:
# ascii val
asc = list(map(lambda x: ord(x), 'prajakta'))
asc

[112, 114, 97, 106, 97, 107, 116, 97]

In [137]:
as1 = list(map(ord, 'prajakta'))
as1

[112, 114, 97, 106, 97, 107, 116, 97]

In [143]:
# string length > 4
l = ['abcd', 'sb', 'dkfhfun','djfjek']
a = list(filter(lambda x: len(str(x)) > 4, l))
a

['dkfhfun', 'djfjek']

In [149]:
# sq of ev no in list
l = [2,4,5,7,6,20]
a = tuple(map(lambda x: x**2, (filter(lambda x: x%2==0,l))))
a

(4, 16, 36, 400)

In [150]:
def chk(x):
    if len(x)>4:
        return True
    else:
        return False

In [151]:
l = ['abcd', 'sb', 'dkfhfun','djfjek']
a = list(map(chk, l))
a

[False, False, True, True]

In [152]:
chr(ord('a')+3)

'd'

In [153]:
ord('x')  # make it 97, y-b, z-c

120

In [159]:
120-97

23

In [161]:
# return vowels --> as upper case ,consonant will be shifted to 3rd right ,Example: zap ---> dAs"
inp = 'hellz'
for i in inp:
    if ord(i)==120:
        i = chr(ord(i)-97)
    elif ord(i)==121:
        i = chr(ord(i)-98)
    elif ord(i)==122:
        i = chr(ord(i)-99)
    else:
        i= chr(ord(i)+3)
    print(i)

k
h
o
o



In [174]:
string = 'hellyz'
new = ''
for letter in string:
    if letter in ('aeiou'):
        new+=letter.upper()
    elif ord(letter)>=97 and ord(letter)<120:
        new+=chr(ord(letter)+3)
    elif letter=='x':
        new+='a'
    elif letter=='y':
        new+='b'
    else:
        new+='c'
print(new)

kEoobc


In [183]:
l1 = [1,2,3,4,5]
l2 = [2,3,4,5]
l3=[7,8,9]

lnew = list(map(lambda x:x*2, (l1,l2,l3)))
lnew

[[1, 2, 3, 4, 5, 1, 2, 3, 4, 5], [2, 3, 4, 5, 2, 3, 4, 5], [7, 8, 9, 7, 8, 9]]

In [185]:
l1 = [1,2,3,4,5]
l2 = [2,3,4,5,6]

lnew = list(map(lambda x,y:x*y, l1,l2)) # map can hv multiple iterable input but filter can hv only 1 iterable input 
lnew

[2, 6, 12, 20, 30]

In [189]:
from itertools import accumulate
l = np.random.randint(1,20,10)
l =list(l)
print(l)
l2=list(accumulate(l, lambda x,y: x+y))
print(l2)

[12, 2, 1, 13, 6, 5, 8, 19, 13, 3]
[12, 14, 15, 28, 34, 39, 47, 66, 79, 82]
